/* US-001 浏览器层：只负责 Three.js 展示、点选、预览和命令提交。 */
(function(){'use strict';
const R=window.M0,$=id=>document.getElementById(id);
const names={king:'帅',rook:'车',horse:'马',cannon:'炮',pawn:'兵',archer:'弓',spearman:'枪兵',advisor:'士'};
const glyph={king:'帅',rook:'车',horse:'马',cannon:'炮',pawn:'兵',archer:'弓',spearman:'枪',advisor:'士'};
const unitName=u=>u.kind==='king'&&u.side==='enemy'?'将':names[u.kind],unitGlyph=u=>u.kind==='king'&&u.side==='enemy'?'将':glyph[u.kind];
const params=new URLSearchParams(window.location?window.location.search:''),fixture=/^P[1-8]$/.test(params.get('fixture')||'')?params.get('fixture'):null,variant=params.get('variant')||undefined;
let state,selected=null,preview=null,rookMode='rook-move',directionGhost=null,paused=false,intentOpen=false,epoch=0;
function initial(){epoch++;selected=preview=directionGhost=null;state=fixture?R.fixtureState(fixture,variant):R.newGame();}
initial();

const scene=new THREE.Scene();scene.background=new THREE.Color(0x101722);scene.fog=new THREE.Fog(0x101722,12,24);
const camera=new THREE.OrthographicCamera(-5,5,5,-5,.1,60);camera.position.set(7.8,11.5,9.5);camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.shadowMap.enabled=true;$('scene').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xcfe2ff,0x4b3424,1.45));const sun=new THREE.DirectionalLight(0xffffff,1.1);sun.position.set(-5,12,7);sun.castShadow=true;scene.add(sun);
const boardGroup=new THREE.Group(),pieceGroup=new THREE.Group(),markGroup=new THREE.Group();scene.add(boardGroup,pieceGroup,markGroup);
const boardMat=new THREE.MeshStandardMaterial({map:boardTexture(),roughness:.72,metalness:.03});const board=new THREE.Mesh(new THREE.BoxGeometry(8.35,.22,8.35),boardMat);board.position.y=-.13;board.receiveShadow=true;boardGroup.add(board);
const rim=new THREE.Mesh(new THREE.BoxGeometry(8.65,.12,8.65),new THREE.MeshStandardMaterial({color:0x62492e,roughness:.85}));rim.position.y=-.25;boardGroup.add(rim);
const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();

function boardTexture(){const c=document.createElement('canvas');c.width=c.height=1024;const x=c.getContext('2d'),m=56,cell=(1024-m*2)/8;x.fillStyle='#d8bd83';x.fillRect(0,0,1024,1024);
 for(let y=0;y<8;y++)for(let col=0;col<8;col++){x.fillStyle=(col+y)%2?'#cfae70':'#dfc58d';x.fillRect(m+col*cell,m+(7-y)*cell,cell,cell)}
 x.strokeStyle='#5b4329';x.lineWidth=4;for(let i=0;i<=8;i++){x.beginPath();x.moveTo(m+i*cell,m);x.lineTo(m+i*cell,1024-m);x.stroke();x.beginPath();x.moveTo(m,m+i*cell);x.lineTo(1024-m,m+i*cell);x.stroke()}
 x.fillStyle='#809ab055';x.fillRect(m,m+4*cell,8*cell,10);x.fillStyle='#31465a';x.font='bold 28px sans-serif';x.textAlign='center';x.fillText('河  界',512,m+4*cell-12);
 function palace(minY){const x0=m+2*cell,x1=m+5*cell,y0=m+(7-(minY+2))*cell,y1=m+(8-minY)*cell;x.strokeStyle='#7a372d';x.lineWidth=5;x.beginPath();x.moveTo(x0,y0);x.lineTo(x1,y1);x.moveTo(x1,y0);x.lineTo(x0,y1);x.stroke()}
 palace(0);palace(5);x.fillStyle='#4a3726';x.font='18px sans-serif';for(let y=0;y<8;y++)for(let col=0;col<8;col++)x.fillText(col+','+y,m+(col+.5)*cell,m+(7-y+.56)*cell);return new THREE.CanvasTexture(c)}
function world(x,y){return{x:x-3.5,z:3.5-y}}
function cellFromPoint(p){const x=Math.floor(p.x+4),y=Math.floor(4-p.z);return R.inside({x,y})?{x,y}:null}
function labelSprite(text,color){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle=color;x.font='bold 66px Microsoft YaHei,sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(text,64,66);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:true}));s.scale.set(.62,.62,.62);s.position.y=.43;return s}
function pieceMesh(u){const ally=u.side==='player',mat=new THREE.MeshStandardMaterial({color:ally?0x8f3228:0x315e8d,roughness:.5,metalness:.12});const geo=ally?new THREE.CylinderGeometry(.36,.39,.24,32):new THREE.BoxGeometry(.7,.24,.7);const g=new THREE.Group(),base=new THREE.Mesh(geo,mat);base.castShadow=true;base.position.y=.16;g.add(base,labelSprite(unitGlyph(u)||'?',ally?'#ffd9b9':'#d9edff'));g.userData.unitId=u.id;g.traverse(o=>o.userData.unitId=u.id);const p=world(u.x,u.y);g.position.set(p.x,0,p.z);return g}
function clear(g){while(g.children.length)g.remove(g.children[0])}
function renderPieces(){clear(pieceGroup);state.units.forEach(u=>pieceGroup.add(pieceMesh(u)))}
function mark(x,y,color=.8,size=.25){const geo=new THREE.CircleGeometry(size,28),mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.62,depthWrite:false});const m=new THREE.Mesh(geo,mat);m.rotation.x=-Math.PI/2;m.position.set(world(x,y).x,.015,world(x,y).z);markGroup.add(m)}
function renderMarks(){clear(markGroup);if(!selected)return;const u=G(selected);if(!u)return;mark(u.x,u.y,0xffd257);R.legalActions(state,u.id).filter(a=>a.type!=='directional'&&(u.kind!=='rook'||a.type===rookMode)).forEach(a=>mark(a.to.x,a.to.y,a.type==='charge'||a.type==='attack'?0xf06c6c:0x65c7ff));if(directionGhost){if(preview&&u.kind==='cannon'&&preview.action.type==='attack'){preview.action.path.slice(0,-1).forEach(p=>mark(p.x,p.y,0xd9a441,.13));const rack=preview.action.path.slice(0,-1).map(p=>R.at(state,p)).find(Boolean);if(rack)mark(rack.x,rack.y,0xb97cff,.31);mark(preview.action.to.x,preview.action.to.y,0xf06c6c,.34)}else directionGhost.forEach(p=>mark(p.x,p.y,0xd9a441))}}
function G(id){return state.units.find(u=>u.id===id)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function unitLine(u){const extra=u.kind==='rook'?`移${u.rookMoveAvailable?'✓':'×'}${u.rookMoveRange}格 · 冲${u.rookChargeAvailable?'✓':'×'}${u.rookChargeRange}格`:`AP ${u.ap}/${u.apLimit}`;return `<div class="unit ${u.id===selected?'selected':''}" data-unit="${esc(u.id)}"><span class="piece-icon">${unitGlyph(u)}</span><span><b>${unitName(u)}</b> · 棋子等级 Lv.${u.level}<small>HP ${u.hp}/${u.maxHp} · SP ${u.sp} · 击杀 ${u.kills}</small></span><span class="ap">${extra}</span></div>`}
function renderAllies(){$('ally-list').innerHTML=state.units.filter(u=>u.side==='player').map(unitLine).join('')||'<span class="empty">无存活单位</span>';$('ally-list').querySelectorAll('[data-unit]').forEach(e=>e.onclick=()=>select(e.dataset.unit))}
function selectedText(u){if(!u)return '<span class="empty">点选棋盘或列表中的我方棋子。</span>';let t=`<b>${names[u.kind]}</b> @ (${u.x},${u.y})<br>棋子等级 Lv.${u.level} · SP ${u.sp} · HP ${u.hp}/${u.maxHp} · 攻击 ${u.attack}`;if(u.kind==='rook')t+=`<br>疾行 ${u.rookMoveRange} 格（${u.rookMoveAvailable?'可用':'已用'}） · 冲击 ${u.rookChargeRange} 格（${u.rookChargeAvailable?'可用':'已用'}） · 震退 ${u.rookPush?'已解锁':'未解锁'}`;else t+=`<br>AP ${u.ap}/${u.apLimit}`;if(u.kind==='archer'||u.kind==='spearman')t+=`<br>${R.CONFIG.directions.map((d,i)=>`${d.name}向 Lv.${2+u.directionPaid[i]}/8 · 攻击 ${1+u.directionPaid[i]} 格`).join('<br>')}`;if(u.kind==='cannon')t+=`<br><b>基础攻击：单格 / 伤害 2 / 隔一子攻击</b><br>本回合行动：${u.ap>0?'<span class="ok">可用</span>':'<span class="warn">已用（下回合可攻击）</span>'}<br>扩散 ${u.cannonMask.toString(2).split('1').length-1}/8（不影响基础攻击）`;return t}
function skillDefs(u){
 const a=[['fortify',null,1,'强健','当前/最大 HP +1',false]];
 if(u.kind==='pawn')a.push(
  ['promote-archer',null,2,'转职弓兵','攻击变 2',false],
  ['promote-spearman',null,2,'转职枪兵','当前/最大 HP +1',false]);
 if(['pawn','archer','spearman'].includes(u.kind))a.push(['combo',null,2,'连动','下回合 AP 上限 +1',false]);
 if(u.kind==='archer'||u.kind==='spearman')R.CONFIG.directions.forEach((d,i)=>a.push(
  ['direction',i,1,`${d.name}向 Lv.${2+u.directionPaid[i]}/8`,`攻击 ${1+u.directionPaid[i]}→${Math.min(7,2+u.directionPaid[i])} 格`,u.directionPaid[i]>=6]));
 if(u.kind==='rook')a.push(
  ['rook-move',null,1,'疾行升级',`${u.rookMoveRange}→${Math.min(7,u.rookMoveRange+1)} 格`,u.rookMoveRange>=7],
  ['rook-charge',null,1,'冲击延伸',`${u.rookChargeRange}→${Math.min(7,u.rookChargeRange+1)} 格`,u.rookChargeRange>=7],
  ['rook-push',null,2,'解锁震退','命中存活目标后推 1 格',u.rookPush]);
 if(u.kind==='cannon')R.CONFIG.splash.forEach((d,i)=>a.push(
  ['cannon-splash',i,1,`扩散 ${d.name}`,'固定目标邻格',Boolean(u.cannonMask&(1<<i))]));
 return a;
}
function renderSkills(u){const root=$('skills');if(!u){root.className='empty';root.textContent='选择棋子后显示。';return}root.className='';root.innerHTML=skillDefs(u).map((d,i)=>{const badPhase=!['player','shop'].includes(state.phase),lack=u.sp<d[2],disabled=d[5]||lack||badPhase,reason=d[5]?'已达上限 / 已解锁':lack?`缺 ${d[2]-u.sp} SP`:badPhase?'当前阶段不可购买':'';return `<button class="skill" data-skill="${d[0]}" data-index="${d[1]===null?'':d[1]}" ${disabled?'disabled':''} title="${reason}"><span>${d[3]}<small>${d[4]}</small></span><span>${d[2]} SP</span></button>${reason?`<div class="reason">${reason}</div>`:''}`}).join('');root.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>buySkill(b.dataset.skill,b.dataset.index===''?undefined:Number(b.dataset.index)))}
function buySkill(skill,index){const u=G(selected),n=u&&R.purchaseUpgrade(state,u.id,skill,index);if(!u||n===state){toast('技能不可购买');return}state=n;cancelPreview(false);postState();toast('技能购买成功')}
function renderModes(u){const rm=$('rook-modes'),ds=$('directions');rm.innerHTML=ds.innerHTML='';if(u&&u.kind==='rook'){rm.innerHTML=`<button data-mode="rook-move" class="${rookMode==='rook-move'?'active':''}" ${!u.rookMoveAvailable||!u.rookChargeAvailable?'disabled':''}>普通移动</button><button data-mode="charge" class="${rookMode==='charge'?'active':''}" ${!u.rookChargeAvailable?'disabled':''}>冲击</button>`;rm.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{rookMode=b.dataset.mode;cancelPreview(false);render()})}if(u&&(u.kind==='archer'||u.kind==='spearman')){ds.innerHTML=R.CONFIG.directions.map((d,i)=>`<button data-dir="${i}">${d.name} Lv.${2+u.directionPaid[i]}</button>`).join('');ds.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>chooseDirection(Number(b.dataset.dir)))} }
function chooseDirection(d){const u=G(selected);if(!u)return;const v=R.CONFIG.directions[d],range=1+u.directionPaid[d];directionGhost=[];for(let i=1;i<=range;i++){const p={x:u.x+v.x*i,y:u.y+v.y*i};if(!R.inside(p))break;directionGhost.push(p);const t=R.at(state,p);if(t&&t.side==='player')break;if(t&&u.kind==='archer')break}preview=R.previewDirection(state,u.id,d);$('directions').querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===d));if(preview)showPreview();else{$('preview-box').innerHTML=`<b>${R.CONFIG.directions[d].name}向预览</b><br>范围 ${directionGhost.map(p=>`(${p.x},${p.y})`).join(' → ')||'棋盘外'}<br><span class="warn">无可命中敌人，不能提交，不消耗 AP。</span>`;$('btn-execute').disabled=true;$('btn-cancel').disabled=false}renderMarks()}
function point(p){return p?`(${p.x},${p.y})`:'无'}
function renderIntents(){const predicted=state.phase==='player'?R.enemyPhase(state).effects:[],byActor=new Map(predicted.map(e=>[e.actor,e])),types={move:'移动',attack:'攻击',charge:'冲击',standby:'待机'},statuses={success:'可执行',cancelled:'将取消',miss:'将落空',removed:'已移除',standby:'待机'};$('intent-list').innerHTML=state.intents.map(i=>{const u=G(i.actor),effect=byActor.get(i.actor),status=effect?statuses[effect.status]||effect.status:'待复验';return `<div class="intent"><span class="order">${i.order}</span>${u?unitName(u):esc(i.actor)} · ${types[i.type]||esc(i.type)}<br>起点 ${point(i.from)} → 目标 ${point(i.to)} · <b>${status}</b></div>`}).join('')||'<span class="empty">无敌方意图</span>';const b=$('btn-intents');b.textContent=`敌方意图（${state.intents.length}）· ${intentOpen?'收起':'展开'}`;b.setAttribute&&b.setAttribute('aria-expanded',String(intentOpen));$('intent-list').classList.toggle('show',intentOpen)}
function hitHTML(h){const before=state.units.find(u=>u.id===h.id),ally=before&&before.side==='player',label=before?`${ally?'友军':'敌军'}${unitName(before)}`:esc(h.id),hp0=before?before.hp:h.damage,hp1=Math.max(0,hp0-h.damage),dead=preview.effect.victims.includes(h.id);return `<div class="hit ${ally?'friendly-fire':''}"><b>${label}</b> @ ${before?point(before):'未知格'}：−${h.damage}，HP ${hp0}→${hp1}${dead?'（阵亡）':''}</div>`}
function showPreview(){if(!preview)return;const a=preview.action,e=preview.effect,actor=G(a.actor),friendly=e.hits.some(h=>{const u=state.units.find(v=>v.id===h.id);return u&&u.side==='player'}),danger=R.king(preview.prediction.state,'player')?preview.prediction.effects.some(x=>x.damage.includes('king')):true,types={move:'移动',attack:'攻击',charge:'冲击',directional:'方向攻击','rook-move':'普通移动'};let charge='',cannon='';if(a.type==='charge'){const push={outside:'失败：棋盘外',palace:'失败：宫界限制',occupied:'失败：目标格被占',pushed:'成功'};charge=`<br>原起点 ${point(a.from)} · 冲击目标 ${point(a.to)}<br>接近点 ${e.approachCell?point(e.approachCell):'无（目标为空）'} · 我车最终落点 ${point(e.actorTo)}`;if(e.pushed)charge+=`<br>震退：${push[e.pushStatus]}，目标到 ${point(e.pushed.to)}`;else if(e.pushStatus)charge+=`<br>震退：${push[e.pushStatus]||e.pushStatus}`;else if(e.hits.length)charge+='<br>震退：未触发';}if(actor&&actor.kind==='cannon'&&a.type==='attack'){const rack=a.path.slice(0,-1).map(p=>R.at(state,p)).find(Boolean),target=R.at(state,a.to);cannon=`<br>炮架 ${rack?`${rack.side==='player'?'友军':'敌军'}${unitName(rack)} @ ${point(rack)}`:'无'}<br>攻击连线 ${point(a.from)} → ${a.path.map(point).join(' → ')}<br>主目标 ${target?`${target.side==='player'?'友军':'敌军'}${unitName(target)}`:'未知'} @ ${point(a.to)} · 预期 −${actor.attack}`;}const hits=e.hits.length?e.hits.map(hitHTML).join(''):'<span class="empty">无伤害</span>';$('preview-box').innerHTML=`<b>${types[a.type]||esc(a.type)}</b>${charge||`：${point(a.from)} → ${point(a.to)}`}${cannon}<br>规则路径 ${a.path.map(point).join(' → ')||'原地'}<br>命中：${hits}${friendly?'<div class="friendly-fire"><b>⚠ 友军误伤风险</b>：执行后会伤害上列友军。</div>':''}<br><span class="${danger?'warn':'ok'}">敌方阶段：${danger?'帅仍受威胁':'帅可存活'}</span>`;$('btn-execute').disabled=false;$('btn-cancel').disabled=false;directionGhost=a.path}
function renderTop(){$('wave').textContent=state.wave+'/2';$('turn').textContent=state.turn;const k=R.king(state,'player'),b=R.king(state,'enemy');$('king-hp').textContent=k?k.hp+'/'+k.maxHp:'0';$('boss-hp').textContent=b?b.hp+'/'+b.maxHp:'0';$('gold').textContent=state.gold;$('kills').textContent=state.kills;if(fixture){$('fixture-badge').style.display='inline';$('fixture-badge').textContent=`测试夹具 ${fixture}${variant?' · '+variant:''}`}}
function idleHint(u){return u&&u.kind==='cannon'&&u.ap<=0?'<span class="warn">本回合已行动，下回合可攻击。</span>':'<span class="empty">选择合法落点，或为弓/枪选择一个方向。</span>'}
function render(){renderTop();renderPieces();renderAllies();const u=G(selected);$('selected-card').innerHTML=selectedText(u);renderModes(u);renderSkills(u);renderIntents();renderMarks();$('btn-end').disabled=state.phase!=='player'&&state.phase!=='shop';$('btn-end').textContent=state.phase==='shop'?'打开商店':'结束回合';if(!preview&&!directionGhost)$('preview-box').innerHTML=idleHint(u);syncOverlays()}
function select(id){const u=G(id);if(!u||u.side!=='player')return;selected=id;preview=directionGhost=null;if(u.kind==='rook')rookMode=u.rookMoveAvailable&&u.rookChargeAvailable?'rook-move':'charge';$('btn-execute').disabled=true;$('btn-cancel').disabled=false;render()}
function cancelPreview(rerender=true){preview=directionGhost=null;$('btn-execute').disabled=true;$('btn-cancel').disabled=!selected;$('preview-box').innerHTML=idleHint(G(selected));if(rerender)render()}
function target(p){const u=G(selected);if(!u||state.phase!=='player')return;const t=R.at(state,p);if(t&&t.side==='player'){select(t.id);return}preview=R.preview(state,u.id,p,u.kind==='rook'?rookMode:undefined);directionGhost=preview?preview.action.path:null;if(preview)showPreview();else{const reason=R.actionReason(state,u.id,p,u.kind==='rook'?rookMode:undefined);$('preview-box').innerHTML=`<span class="warn">${esc(reason)}</span>`;$('btn-execute').disabled=true;toast(reason)}renderMarks()}
function execute(){if(!preview)return;const r=R.submitAction(state,preview.action);if(!r.effect){toast('预览已过期，请重新选择');cancelPreview();return}state=r.state;selected=state.units.some(u=>u.id===selected)?selected:null;cancelPreview(false);postState()}
function postState(){if(state.phase==='player'&&R.dangerNow(state)){const checked=R.checkmate(state);if(checked!==state)state=checked}render()}
function toast(msg){const b=$('banner');b.textContent=msg;b.className='show';clearTimeout(toast.t);toast.t=setTimeout(()=>b.className='',1800)}
function syncOverlays(){$('ov-shop').classList.toggle('show',state.phase==='shop');$('ov-result').classList.toggle('show',state.phase==='result');if(state.phase==='shop'){$('shop-status').textContent=`金币 ${state.gold} · ${state.bought?'已购买队友':'尚未购买'}`;$('btn-buy-horse').disabled=state.bought||state.gold<2;$('btn-buy-cannon').disabled=state.bought||state.gold<2}if(state.phase==='result'){$('result-title').textContent=state.result==='victory'?'胜利':state.result==='mate'?'将死':'主帅阵亡';$('result-text').textContent=`波次 ${state.wave} · 回合 ${state.turn} · 总击杀 ${state.kills}`}}
function restart(){paused=false;$('ov-pause').classList.remove('show');$('ov-confirm').classList.remove('show');initial();render();toast(fixture?`已重置 ${fixture}`:'已重新开始')}
renderer.domElement.addEventListener('pointerup',e=>{if(paused||state.phase!=='player')return;const rect=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-rect.left)/rect.width*2-1;mouse.y=-(e.clientY-rect.top)/rect.height*2+1;ray.setFromCamera(mouse,camera);const pieces=ray.intersectObjects(pieceGroup.children,true);if(pieces.length){const id=pieces[0].object.userData.unitId,u=G(id);if(u&&u.side==='player'){select(id);return}if(u&&selected){target({x:u.x,y:u.y});return}}const hit=ray.intersectObject(board)[0];if(hit){const p=cellFromPoint(hit.point);if(p)target(p)}});
$('btn-execute').onclick=execute;$('btn-cancel').onclick=()=>{selected=null;cancelPreview()};$('btn-end').onclick=()=>{if(state.phase==='shop'){syncOverlays();return}const predicted=R.enemyPhase(state),hits=predicted.effects.filter(e=>e.damage.includes('king')).length;$('confirm-text').innerHTML=hits?`预计主帅受击 <b class="warn">${hits}</b> 次。`:'当前预告未命中主帅。';$('ov-confirm').classList.add('show')};$('btn-confirm-no').onclick=()=>$('ov-confirm').classList.remove('show');$('btn-confirm-yes').onclick=()=>{$('ov-confirm').classList.remove('show');const out=R.endTurn(state);state=out.state;selected=preview=directionGhost=null;postState();toast(`敌方阶段：${out.effects.filter(e=>e.status==='success').length} 个意图执行`)};
$('btn-pause').onclick=()=>{paused=true;$('ov-pause').classList.add('show')};$('btn-resume').onclick=()=>{paused=false;$('ov-pause').classList.remove('show')};$('btn-restart-1').onclick=$('btn-restart-2').onclick=restart;
$('btn-intents').onclick=()=>{intentOpen=!intentOpen;renderIntents()};
for(const kind of ['horse','cannon'])$('btn-buy-'+kind).onclick=()=>{const n=R.buy(state,kind);if(n===state)return;state=n;render();toast(`已购买${names[kind]}`)};$('btn-shop-upgrades').onclick=()=>{$('ov-shop').classList.remove('show');toast('选择单位购买技能；“打开商店”可返回')};$('btn-next-wave').onclick=()=>{state=R.nextWave(state);selected=null;postState()};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.phase==='player'){paused=true;$('ov-pause').classList.add('show')}});
function resize(){const w=window.innerWidth||1280,mobile=w<=900,rect=$('scene').getBoundingClientRect(),sceneW=Math.max(1,Math.round(rect.width||w)),sceneH=Math.max(1,Math.round(rect.height||(window.innerHeight||800)*(mobile ? .52 : 1)));renderer.setSize(sceneW,sceneH);camera.position.set(0,12.5,8);camera.lookAt(0,0,0);const aspect=sceneW/sceneH,size=Math.max(5.4,4.7/aspect);camera.left=-size*aspect;camera.right=size*aspect;camera.top=size;camera.bottom=-size;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();
function loop(){requestAnimationFrame(loop);if(!paused){pieceGroup.rotation.y=Math.sin(performance.now()/1700)*.005;renderer.render(scene,camera)}}loop();postState();
window.__M0_DEBUG__={getState:()=>R.copy(state),setState:s=>{state=R.copy(s);selected=preview=directionGhost=null;postState()},select,target,execute,setRookMode:m=>{rookMode=m},upgrade:(id,skill,index)=>{selected=id;buySkill(skill,index)},endTurn:()=>{state=R.endTurn(state).state;postState()},restart,getEpoch:()=>epoch};
})();
