// US-001 纯规则引擎：8×8、确定性、无 DOM / 渲染 / IO。
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.M0=factory();})(typeof self!=='undefined'?self:this,function(){
'use strict';
var C={width:8,height:8,river:3.5,reward:2,price:2,
 playerPalace:{minX:2,maxX:4,minY:0,maxY:2,cx:3,cy:1},enemyPalace:{minX:2,maxX:4,minY:5,maxY:7,cx:3,cy:6},
 spawns:{king:{x:3,y:0},rook:{x:0,y:0},horse:{x:2,y:0},cannon:{x:1,y:2}},
 waves:[
  [['pawn',0,4],['pawn',3,4],['pawn',6,4],['rook',7,6],['cannon',0,6],['advisor',2,7],['advisor',4,7],['king',3,7]],
  [['pawn',1,4],['pawn',4,4],['pawn',7,4],['rook',0,6],['cannon',6,6],['advisor',2,7],['advisor',4,7],['king',3,7]]],
 directions:[{x:0,y:1,name:'前'},{x:1,y:0,name:'右'},{x:0,y:-1,name:'后'},{x:-1,y:0,name:'左'}],
 splash:[{x:0,y:1,name:'N'},{x:1,y:1,name:'NE'},{x:1,y:0,name:'E'},{x:1,y:-1,name:'SE'},{x:0,y:-1,name:'S'},{x:-1,y:-1,name:'SW'},{x:-1,y:0,name:'W'},{x:-1,y:1,name:'NW'}]};
function cp(v){return JSON.parse(JSON.stringify(v));}function same(a,b){return a.x===b.x&&a.y===b.y;}function inside(p){return Number.isInteger(p.x)&&Number.isInteger(p.y)&&p.x>=0&&p.x<8&&p.y>=0&&p.y<8;}
function at(s,p){return s.units.find(function(u){return same(u,p);});}function king(s,side){return s.units.find(function(u){return u.side===side&&u.kind==='king';});}function pawnish(u){return u.kind==='pawn'||u.kind==='archer'||u.kind==='spearman';}
function palace(side){return side==='player'?C.playerPalace:C.enemyPalace;}function inPalace(side,p){var q=palace(side);return p.x>=q.minX&&p.x<=q.maxX&&p.y>=q.minY&&p.y<=q.maxY;}
function palaceDiag(side,a,b){var q=palace(side);return Math.abs(a.x-b.x)===1&&Math.abs(a.y-b.y)===1&&((a.x===q.cx&&a.y===q.cy)||(b.x===q.cx&&b.y===q.cy));}
function line(a,b){if(a.x!==b.x&&a.y!==b.y)return[];var dx=Math.sign(b.x-a.x),dy=Math.sign(b.y-a.y),o=[];for(var x=a.x+dx,y=a.y+dy;x!==b.x||y!==b.y;x+=dx,y+=dy)o.push({x:x,y:y});o.push({x:b.x,y:b.y});return o;}
function hp(kind,side){if(kind==='king')return side==='player'?3:2;if(kind==='rook'||kind==='cannon')return 2;return 1;}function attack(kind){return kind==='archer'||kind==='cannon'?2:1;}
function unit(id,side,kind,x,y){var h=hp(kind,side),p=side==='player';return{id:id,side:side,kind:kind,x:x,y:y,hp:h,maxHp:h,attack:attack(kind),level:1,kills:0,sp:0,ap:p?1:0,apLimit:p?1:0,combo:0,fortify:0,directionPaid:[0,0,0,0],cannonMask:0,rookMoveRange:3,rookChargeRange:1,rookPush:false,rookMoveAvailable:p&&kind==='rook',rookChargeAvailable:p&&kind==='rook',acted:false};}
function acted(u){u.acted=u.kind==='rook'?!u.rookMoveAvailable&&!u.rookChargeAvailable:u.ap<=0;}function resetTurn(u){if(u.side!=='player')return;if(u.kind==='rook'){u.ap=u.apLimit=1;u.rookMoveAvailable=u.rookChargeAvailable=true;}else{u.apLimit=pawnish(u)?1+u.combo:1;u.ap=u.apLimit;}acted(u);}
function emptyState(units){return{units:units||[],intents:[],phase:'player',wave:1,turn:1,gold:0,bought:false,kills:0,highestLevel:1,result:undefined,revision:0};}
function addWave(s){C.waves[s.wave-1].forEach(function(w,i){s.units.push(unit('w'+s.wave+'-'+i,'enemy',w[0],w[1],w[2]));});s.intents=generateIntents(s);}function newGame(){var s=emptyState([unit('king','player','king',3,0),unit('rook','player','rook',0,0)]);addWave(s);return s;}
function pawnMove(u,dx,dy){var f=u.side==='player'?1:-1,cross=u.side==='player'?u.y>=4:u.y<=3;return dx===0&&dy===f||cross&&Math.abs(dx)===1&&dy===0;}
function ordinary(s,u,to){if(!inside(to)||same(u,to))return;var t=at(s,to);if(t&&t.side===u.side)return;var dx=to.x-u.x,dy=to.y-u.y,ax=Math.abs(dx),ay=Math.abs(dy),ok=false,path=[cp(to)];
 if(u.kind==='king')ok=inPalace(u.side,u)&&inPalace(u.side,to)&&(ax+ay===1||palaceDiag(u.side,u,to));
 else if(u.kind==='advisor')ok=inPalace(u.side,u)&&inPalace(u.side,to)&&palaceDiag(u.side,u,to);
 else if(pawnish(u))ok=u.kind==='pawn'||!t?pawnMove(u,dx,dy):false;
 else if(u.kind==='horse'){var leg={x:u.x+(ax===2?Math.sign(dx):0),y:u.y+(ay===2?Math.sign(dy):0)};ok=ax*ay===2&&!at(s,leg);}
 else if(u.kind==='cannon'&&(dx===0||dy===0)){path=line(u,to);var screens=path.slice(0,-1).filter(function(p){return at(s,p);}).length;ok=t?screens===1:screens===0&&path.length<=3;}
 if(ok)return{actor:u.id,from:{x:u.x,y:u.y},to:cp(to),type:t?'attack':'move',path:path};}
function rookAction(s,u,to,mode){if(!inside(to)||same(u,to)||(u.x!==to.x&&u.y!==to.y))return;var t=at(s,to);if(t&&t.side===u.side)return;var path=line(u,to);if(path.slice(0,-1).some(function(p){return at(s,p);}))return;
 if(mode==='rook-move'&&!t&&u.rookMoveAvailable&&u.rookChargeAvailable&&path.length<=u.rookMoveRange)return{actor:u.id,from:{x:u.x,y:u.y},to:cp(to),type:mode,path:path};
 if(mode==='charge'&&u.rookChargeAvailable&&path.length<=u.rookChargeRange)return{actor:u.id,from:{x:u.x,y:u.y},to:cp(to),type:mode,path:path};}
function enemyRookActions(s,u){var o=[];for(var y=0;y<8;y++)for(var x=0;x<8;x++){var to={x:x,y:y},t=at(s,to),p=line(u,to);if(!p.length||p.slice(0,-1).some(function(q){return at(s,q);})||t&&t.side===u.side)continue;if(!t&&p.length<=3)o.push({actor:u.id,from:{x:u.x,y:u.y},to:to,type:'move',path:p});if(t&&p.length<=1)o.push({actor:u.id,from:{x:u.x,y:u.y},to:to,type:'charge',path:p});}return o;}
function actionAt(s,u,to,mode){if(!u)return;if(u.kind==='rook'){if(u.side==='enemy')return enemyRookActions(s,u).find(function(a){return same(a.to,to)&&(!mode||a.type===mode);});return rookAction(s,u,to,mode||(at(s,to)?'charge':'rook-move'));}return ordinary(s,u,to);}
function directionalAction(s,id,d){var u=s.units.find(function(v){return v.id===id;});if(!u||u.side!=='player'||u.kind!=='archer'&&u.kind!=='spearman'||!Number.isInteger(d)||d<0||d>3||u.ap<=0)return;var v=C.directions[d],range=1+u.directionPaid[d],targets=[],path=[];for(var i=1;i<=range;i++){var p={x:u.x+v.x*i,y:u.y+v.y*i};if(!inside(p))break;path.push(p);var t=at(s,p);if(!t)continue;if(t.side===u.side)break;targets.push(t.id);if(u.kind==='archer')break;}if(targets.length)return{actor:u.id,from:{x:u.x,y:u.y},to:cp(path[path.length-1]),type:'directional',direction:d,path:path,targets:targets};}
function legalActions(s,id){var u=s.units.find(function(v){return v.id===id;});if(!u)return[];if(u.side==='enemy'&&u.kind==='rook')return enemyRookActions(s,u);var o=[];for(var y=0;y<8;y++)for(var x=0;x<8;x++){var p={x:x,y:y};if(u.side==='player'&&u.kind==='rook'){var m=rookAction(s,u,p,'rook-move'),c=rookAction(s,u,p,'charge');if(m)o.push(m);if(c)o.push(c);}else{var a=ordinary(s,u,p);if(a)o.push(a);}}if(u.side==='player'&&(u.kind==='archer'||u.kind==='spearman'))for(var d=0;d<4;d++){var q=directionalAction(s,id,d);if(q)o.push(q);}return o;}
function award(s,u,ids){if(!u||u.side!=='player'||!ids.length)return;u.kills+=ids.length;u.level+=ids.length;u.sp+=ids.length;s.kills+=ids.length;s.highestLevel=Math.max(s.highestLevel,u.level);}
function removeDead(s,targets,u){var dead=targets.filter(function(t){return t.hp<=0;});s.units=s.units.filter(function(v){return dead.indexOf(v)<0;});award(s,u,dead.filter(function(v){return v.side==='enemy';}).map(function(v){return v.id;}));return dead.map(function(v){return v.id;});}
function canPush(u,p){return inside(p)&&(u.kind!=='king'&&u.kind!=='advisor'||inPalace(u.side,p));}
function terminal(s){if(!king(s,'player')){s.phase='result';s.result='dead';}else if(!king(s,'enemy')){if(s.wave===1){s.phase='shop';s.gold+=2;s.units=s.units.filter(function(u){return u.side==='player';});}else{s.phase='result';s.result='victory';}}if(s.phase!=='player')s.intents=[];}
function apply(s,a,consume){var u=s.units.find(function(v){return v.id===a.actor;}),e={actor:a.actor,to:cp(a.from),actorTo:cp(a.from),path:cp(a.path||[]),approachCell:null,victims:[],damage:[],hits:[],pushed:null,pushStatus:null,status:'success'};if(!u){e.status='removed';return e;}
 if(a.type==='move'||a.type==='rook-move'){u.x=a.to.x;u.y=a.to.y;e.to=cp(a.to);}
 else if(a.type==='charge'){var t=at(s,a.to),dx=Math.sign(a.to.x-u.x),dy=Math.sign(a.to.y-u.y);if(!t){u.x=a.to.x;u.y=a.to.y;}else{var near={x:a.to.x-dx,y:a.to.y-dy},before=t.hp;u.x=near.x;u.y=near.y;e.approachCell=cp(near);t.hp-=u.attack;e.damage.push(t.id);e.hits.push({id:t.id,damage:Math.min(before,u.attack)});if(t.hp<=0){e.victims=removeDead(s,[t],u);u.x=a.to.x;u.y=a.to.y;}else if(u.rookPush){var push={x:t.x+dx,y:t.y+dy};if(!inside(push))e.pushStatus='outside';else if(!canPush(t,push))e.pushStatus='palace';else if(at(s,push))e.pushStatus='occupied';else{t.x=push.x;t.y=push.y;e.pushed={id:t.id,to:push};e.pushStatus='pushed';}}}e.to=e.actorTo={x:u.x,y:u.y};}
 else{var targets=[];if(a.type==='directional')targets=a.targets.map(function(id){return s.units.find(function(v){return v.id===id;});}).filter(Boolean);else if(u.kind==='cannon'){var cells=[cp(a.to)];C.splash.forEach(function(d,i){if(u.cannonMask&1<<i){var p={x:a.to.x+d.x,y:a.to.y+d.y};if(inside(p))cells.push(p);}});targets=cells.map(function(p){return at(s,p);}).filter(Boolean);}else{var one=at(s,a.to);if(one)targets=[one];}targets.sort(function(a,b){return a.id.localeCompare(b.id);});targets.forEach(function(t){var before=t.hp;t.hp-=u.attack;e.damage.push(t.id);e.hits.push({id:t.id,damage:Math.min(before,u.attack)});});e.victims=removeDead(s,targets,u);e.to=e.actorTo={x:u.x,y:u.y};}
 e.actorTo={x:u.x,y:u.y};if(consume&&u.side==='player'){if(a.type==='rook-move')u.rookMoveAvailable=false;else if(u.kind==='rook'){u.ap=0;u.rookMoveAvailable=u.rookChargeAvailable=false;}else u.ap=Math.max(0,u.ap-1);acted(u);}terminal(s);return e;}
function submitAction(s,a){var u=s.units.find(function(v){return v.id===a.actor;});if(Number.isInteger(a.revision)&&a.revision!==s.revision||s.phase!=='player'||!u||u.side!=='player'||(u.kind==='rook'?!u.rookMoveAvailable&&!u.rookChargeAvailable:u.ap<=0))return{state:s};var legal=a.type==='directional'?directionalAction(s,u.id,a.direction):actionAt(s,u,a.to,a.type);if(!legal)return{state:s};var n=cp(s),effect=apply(n,legal,true);n.revision=(s.revision||0)+1;legal.revision=s.revision||0;return{state:n,effect:effect,action:legal};}
function submit(s,id,to,mode){var u=s.units.find(function(v){return v.id===id;});if(s.phase!=='player'||!u||u.side!=='player'||u.kind!=='rook'&&u.ap<=0||u.kind==='rook'&&!u.rookMoveAvailable&&!u.rookChargeAvailable)return{state:s};var a=actionAt(s,u,to,mode);return a?submitAction(s,a):{state:s};}function submitDirection(s,id,d){var a=directionalAction(s,id,d);return a?submitAction(s,a):{state:s};}
function generateIntents(s){var k=king(s,'player');if(!k)return[];var out=[],order=0;s.units.forEach(function(u){if(u.side!=='enemy')return;order++;var as=legalActions(s,u.id);function pri(a){var t=at(s,a.to);return t?(t.kind==='king'?0:t.kind==='rook'?1:2):3;}as.sort(function(a,b){return pri(a)-pri(b)||(pri(a)===3?Math.abs(a.to.x-k.x)+Math.abs(a.to.y-k.y)-Math.abs(b.to.x-k.x)-Math.abs(b.to.y-k.y):0)||a.to.y-b.to.y||a.to.x-b.to.x||a.type.localeCompare(b.type);});out.push(as.length?Object.assign(cp(as[0]),{order:order}):{actor:u.id,from:{x:u.x,y:u.y},to:{x:u.x,y:u.y},type:'standby',path:[],order:order});});return out;}
function revalidate(s,i){var u=s.units.find(function(v){return v.id===i.actor;});if(!u)return;if(i.type==='standby')return cp(i);var occ=at(s,i.to);if(occ&&occ.side===u.side||i.type==='move'&&occ)return;if(i.type==='attack'&&!occ){if(u.kind!=='cannon')return{missOnly:true};var cannonPath=line(u,i.to),screens=cannonPath.slice(0,-1).filter(function(p){return at(s,p);}).length;if(screens!==1)return;return{actor:u.id,from:{x:u.x,y:u.y},to:cp(i.to),type:'attack',path:cannonPath};}if(u.kind==='rook'&&i.type==='charge'){var chargePath=line(u,i.to);if(!inside(i.to)||same(u,i.to)||!chargePath.length||chargePath.length>u.rookChargeRange||chargePath.slice(0,-1).some(function(p){return at(s,p);}))return;return{actor:u.id,from:{x:u.x,y:u.y},to:cp(i.to),type:'charge',path:chargePath};}if(u.kind==='rook')return actionAt(s,u,i.to,'move');return actionAt(s,u,i.to);}
function enemyPhase(s){var n=cp(s),effects=[];if(s.phase!=='player')return{state:n,effects:effects};s.intents.forEach(function(i){if(n.phase!=='player')return;var u=n.units.find(function(v){return v.id===i.actor;});if(!u){effects.push({actor:i.actor,to:cp(i.from),victims:[],damage:[],hits:[],status:'removed'});return;}if(i.type==='standby'){effects.push({actor:i.actor,to:cp(i.from),victims:[],damage:[],hits:[],status:'standby'});return;}var a=revalidate(n,i);if(!a){effects.push({actor:i.actor,to:cp(i.from),victims:[],damage:[],hits:[],status:'cancelled'});return;}if(a.missOnly){effects.push({actor:i.actor,to:cp(i.from),victims:[],damage:[],hits:[],status:'miss'});return;}var empty=!at(n,i.to),e=apply(n,a,false);if(i.type==='attack'&&empty)e.status='miss';effects.push(e);});return{state:n,effects:effects};}
function endTurn(s){if(s.phase!=='player')return{state:s,effects:[]};var r=enemyPhase(s),n=r.state;n.revision=(s.revision||0)+1;if(n.phase==='player'){n.turn++;n.units.forEach(resetTurn);n.intents=generateIntents(n);}return{state:n,effects:r.effects};}
function purchaseUpgrade(s,id,skill,index){if(s.phase!=='player'&&s.phase!=='shop')return s;var src=s.units.find(function(u){return u.id===id&&u.side==='player';});if(!src)return s;var cost=skill==='promote-archer'||skill==='promote-spearman'||skill==='combo'||skill==='rook-push'?2:1;if(src.sp<cost)return s;var ok=skill==='fortify'||((skill==='promote-archer'||skill==='promote-spearman')&&src.kind==='pawn')||(skill==='combo'&&pawnish(src))||(skill==='direction'&&(src.kind==='archer'||src.kind==='spearman')&&Number.isInteger(index)&&index>=0&&index<4&&src.directionPaid[index]<6)||(skill==='rook-move'&&src.kind==='rook'&&src.rookMoveRange<7)||(skill==='rook-charge'&&src.kind==='rook'&&src.rookChargeRange<7)||(skill==='rook-push'&&src.kind==='rook'&&!src.rookPush)||(skill==='cannon-splash'&&src.kind==='cannon'&&Number.isInteger(index)&&index>=0&&index<8&&!(src.cannonMask&1<<index));if(!ok)return s;var n=cp(s),u=n.units.find(function(v){return v.id===id;});n.revision=(s.revision||0)+1;u.sp-=cost;if(skill==='fortify'){u.fortify++;u.maxHp++;u.hp++;}else if(skill==='promote-archer'){u.kind='archer';u.attack=2;}else if(skill==='promote-spearman'){u.kind='spearman';u.maxHp++;u.hp++;}else if(skill==='combo')u.combo++;else if(skill==='direction')u.directionPaid[index]++;else if(skill==='rook-move')u.rookMoveRange++;else if(skill==='rook-charge')u.rookChargeRange++;else if(skill==='rook-push')u.rookPush=true;else if(skill==='cannon-splash')u.cannonMask|=1<<index;return n;}
function buy(s,kind){if(s.phase!=='shop'||s.bought||s.gold<2||kind!=='horse'&&kind!=='cannon')return s;var n=cp(s),p=C.spawns[kind];n.revision=(s.revision||0)+1;n.gold-=2;n.bought=true;n.units.push(unit(kind,'player',kind,p.x,p.y));return n;}
function nextWave(s){if(s.phase!=='shop')return s;var n=cp(s);n.revision=(s.revision||0)+1;n.wave=2;n.phase='player';n.result=undefined;n.units.forEach(function(u){var p=u.id==='king'?C.spawns.king:u.id==='rook'?C.spawns.rook:C.spawns[u.kind];if(p){u.x=p.x;u.y=p.y;}resetTurn(u);});addWave(n);return n;}
function upgradeChoices(s){var o=[];s.units.filter(function(u){return u.side==='player'&&u.sp>0;}).forEach(function(u){function add(skill,i){var n=purchaseUpgrade(s,u.id,skill,i);if(n!==s)o.push({unit:u.id,skill:skill,index:i,state:n});}add('fortify');if(pawnish(u))add('combo');if(u.kind==='pawn'){add('promote-archer');add('promote-spearman');}if(u.kind==='archer'||u.kind==='spearman')for(var d=0;d<4;d++)add('direction',d);if(u.kind==='rook'){add('rook-move');add('rook-charge');add('rook-push');}if(u.kind==='cannon')for(var i=0;i<8;i++)add('cannon-splash',i);});return o;}
function* escapeAnalysis(s){var seen=new Set(),nodes=0;function* search(cur,plan){nodes++;yield;if(cur.phase==='shop'||cur.result==='victory')return plan;if(cur.phase==='result')return;var resolved=enemyPhase(cur).state;if(king(resolved,'player')&&resolved.result!=='dead')return plan;var key=JSON.stringify([cur.units,cur.intents]);if(seen.has(key))return;seen.add(key);var ps=cur.units.filter(function(u){return u.side==='player';});for(var i=0;i<ps.length;i++){var as=legalActions(cur,ps[i].id);for(var j=0;j<as.length;j++){var r=submitAction(cur,as[j]);if(!r.effect)continue;var found=yield* search(r.state,plan.concat([as[j]]));if(found)return found;}}var ups=upgradeChoices(cur);for(var q=0;q<ups.length;q++){var step={type:'upgrade',actor:ups[q].unit,skill:ups[q].skill,index:ups[q].index};var safe=yield* search(ups[q].state,plan.concat([step]));if(safe)return safe;}}var plan=yield* search(cp(s),[]);return{safe:!!plan,plan:plan||[],nodes:nodes};}
function analyze(s){var it=escapeAnalysis(s),v=it.next();while(!v.done)v=it.next();return v.value;}function dangerNow(s){var k=king(s,'player');return!k||enemyPhase(s).effects.some(function(e){return e.damage.indexOf(k.id)>=0;});}function checkmate(s){if(s.phase!=='player'||analyze(s).safe)return s;var n=cp(s);n.phase='result';n.result='mate';n.intents=[];return n;}
function preview(s,id,to,mode){var r=submit(s,id,to,mode);return r.effect?{action:r.action,effect:r.effect,state:r.state,prediction:enemyPhase(r.state)}:null;}function previewDirection(s,id,d){var r=submitDirection(s,id,d);return r.effect?{action:r.action,effect:r.effect,state:r.state,prediction:enemyPhase(r.state)}:null;}
function fixtureState(name,variant){var s=emptyState([unit('king','player','king',3,0),unit('boss','enemy','king',3,7)]);function add(u){s.units.push(u);return u;}if(name==='P1'){add(unit('pawn','player','pawn',2,5));add(unit('e1','enemy','pawn',2,6));add(unit('e2','enemy','pawn',3,5));}else if(name==='P2'){var r=add(unit('rook','player','rook',1,4));r.rookChargeRange=3;r.rookPush=true;add(unit('target','enemy','rook',4,4));if(variant==='blocked')add(unit('block','enemy','pawn',5,4));}else if(name==='P3'){var c=add(unit('cannon','player','cannon',4,1));c.sp=2;add(unit('screen','enemy','pawn',4,3));add(unit('target','enemy','rook',4,5));add(unit('north','enemy','rook',4,6));add(unit('east','enemy','rook',5,5));}else if(name==='P4'){var c4=add(unit('cannon','player','cannon',4,1));c4.sp=1;add(unit('screen','player','horse',4,3));add(unit('target','enemy','rook',4,4));}else if(name==='P5'){var c5=add(unit('cannon','player','cannon',2,1));c5.sp=8;add(unit('screen','enemy','pawn',2,3));add(unit('target','enemy','rook',2,5));}else if(name==='P6'){var k=king(s,'player');k.hp=1;k.sp=1;k.ap=0;acted(k);var er=add(unit('threat','enemy','rook',3,1));s.intents=[{actor:er.id,from:{x:3,y:1},to:{x:3,y:0},type:'charge',path:[{x:3,y:0}],order:1}];return s;}else if(name==='P7'){var p=add(unit('pawn','player',variant==='spearman'?'spearman':'archer',2,4));p.directionPaid[0]=2;p.attack=p.kind==='archer'?2:1;add(unit('near','enemy','pawn',2,5));add(unit('far','enemy','pawn',2,7));if(variant==='blocked')add(unit('block','player','horse',2,6));}else if(name==='P8'){if(variant==='enemy-empty'){var er8=add(unit('enemy-rook','enemy','rook',0,4));s.intents=[{actor:er8.id,from:{x:0,y:4},to:{x:0,y:3},type:'charge',path:[{x:0,y:3}],order:1}];return s;}var r8=add(unit('rook','player','rook',1,1));r8.rookChargeRange=3;if(variant==='kill')add(unit('target','enemy','pawn',4,1));else if(variant==='survive')add(unit('target','enemy','rook',4,1));}s.intents=s.units.filter(function(u){return u.side==='enemy';}).map(function(u,i){return{actor:u.id,from:{x:u.x,y:u.y},to:{x:u.x,y:u.y},type:'standby',path:[],order:i+1};});return s;}
return{CONFIG:C,copy:cp,same:same,at:at,king:king,unit:unit,emptyState:emptyState,newGame:newGame,inside:inside,inPalace:inPalace,line:line,actionAt:actionAt,directionalAction:directionalAction,legalActions:legalActions,submit:submit,submitDirection:submitDirection,submitAction:submitAction,generateIntents:generateIntents,enemyPhase:enemyPhase,endTurn:endTurn,purchaseUpgrade:purchaseUpgrade,buy:buy,nextWave:nextWave,dangerNow:dangerNow,escapeAnalysis:escapeAnalysis,analyze:analyze,checkmate:checkmate,preview:preview,previewDirection:previewDirection,fixtureState:fixtureState,resetTurn:resetTurn};
});
